### ISSUE TITLE
RFC: Use Cases

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/codelift#68]
# What scenarios would a GUI help you?

There are several tools investigating the no/low-code space, but what's missing is **your** input on what gaps these tools can close for you.

_Below are scenarios that I've found frustrating and would like a GUI to solve. Comment with yours!_

## Use Cases

- [x] Visualize Tailwind CSS classes before applying them.

	When working with Tailwind CSS in the editor, I have to save them in my code & wait for the page to refresh to know if it looks right or not.  The GUI should allow me to select an HTML element, preview the Tailwind classes, and click-to-apply them without going into my code.

- [ ] Open in IDE (#47)

	When selecting an element/component, the GUI should give the option to open that file+line in the IDE (e.g. VS Code).

- [ ] Prompt for (or auto-install) missing NPM dependencies. (#61)

	When working on a project & needing a dependency (e.g. `lodash`), I often <kbd>Ctrl-C</kbd> or <kbd>Ctrl-Z</kbd> to `yarn add lodash`, then re-run the server.  The GUI should notice the missing dependency & prompt to install it (+ types?)

- [ ] Edit Component Props

	When working with HTML elements, editing styles can make sense.  When selecting a Component, the GUI should allow me to edit its props.

- [ ] Edit Text

	When selecting an HTML element, the GUI should allow me to preview & edit the text within it.

**Comment by ericclemmons** [comment]
I guess only I care :'(

**Comment by divyenduz** [comment]
If you follow Rick and Morty: https://getyarn.io/yarn-clip/b360e6ca-20f1-4e4c-b2a0-e48b4e7dd92d

I was trying to make this work for plain old HTML today (using a static file server `serve`)! I want WYSIWYG-ish editor for HTML and was exploring this. 

Of course, I immediately ran into "Permission denied to access property "document" on cross-origin object". 

Maybe this would be out of scope for `codelift` but for plain HTML (maybe even for React?), when you have access to the file system, instead of using `iframe` to load the 3rd party server, maybe it is possible to copy and render HTML (might be very tricky because then you have to build navigation 🤔)

What do you think? Out of scope probably right? What I want to build is much more smaller in scope but a different thing.
